@startuml

header 20200426

title 设备风险安全报警流程图

actor 用户
participant 服务器
participant 前端

group 上报
用户 -> 服务器 : 调用接口"/record/uploadData"，上报数据
note left : 司机端启用应用、进入主页时检测，\n存在异常时才上报
activate 服务器
服务器 --> 服务器 : 解析获取request里面的ip、当前服务器时间
服务器 --> 服务器 : 满足条件则保存数据到数据库：RecordType=1，\ncontent不为空 ，appInfo不为空且appInfo.appKey不为空\n
服务器 --> 服务器 : 根据appkey查询应用信息，redis缓存在app_info组
服务器 --> 服务器 : 如果应用存在，保存报警记录到risk_record表，\n并将该风险设备用户信息保存到risk_user表
deactivate 服务器
end

group 查询
前端 -> 服务器 : 调用接口"/record/queryRiskListForLayui"，分页请求数据
note left : 不会做拦截
activate 服务器
服务器 --> 服务器 : 根据搜索条件，数据库中查数据
note left : 筛选条件：应用类型、app版本、设备型号、\n设备品牌、手机号、设备id、时间段
deactivate 服务器
服务器 --> 前端 : 返回满足条件要求的数据列表

end

@enduml