@startuml

header 20200421

title 前端用户中心登录流程图

participant 前端
participant 服务器
participant 数据库
participant redis

group 【/user/login】 token无效时才需要登录，存在有效token时直接请求
前端 -> 服务器 : 请求登录接口，传值account、password（未加密）
activate 服务器
服务器 -> 服务器 : 登录传值的密码进行MD5加密
服务器 -> 数据库 : 拿账号和加密后的密码\n在数据库中查找用户是否存在
服务器 --> 前端 : 不存在，返回提示"用户不存在或密码错误"
服务器 --> 前端 : 存在。\n账号被禁用返回提示"用户已被禁用"；\n有效用户：返回用户信息，Cookie中设置7天有效的token，\nSession中保存用户信息在user中

服务器 --> redis : 存在且有效，redis中user_info组缓存token为key，\n用户信息为value，有效期7天
deactivate 服务器
end

group 【/user/info】存在有效token，请求用户信息
前端 -> 服务器 : 请求用户信息接口（header中带token）
activate 服务器
服务器 -> 服务器 : API拦截器根据token在redis中查找到用户信息，\n保存在request的userData属性中
服务器 --> 前端 : 不存在，返回提示"用户不存在或密码错误"\n（用户一旦登录过，token给出去则redis中就进行了缓存）
服务器 --> 前端 : 存在。\n账号被禁用返回提示"用户已被禁用"；\n有效用户：返回用户信息，Session中保存用户信息在user中
deactivate 服务器
end

@enduml