@startuml

header 20200316

title 获取服务号token流程图

group 获取服务号token
:APP记录平台;
if (本地检查是否存在有效token) then (存在，直接返回)
elseif (数据库检查下啊是否存在有效token) then (存在，直接返回。且保存在本地)
else (不存在)
    : 请求微信平台接口获取到token、\n有效期，保存在本地、数据库;
endif
:APP记录平台拿到token;
end group

@enduml