@startuml

header 20200316

title 获取服务号token流程图

(*) --> [start process] "获取服务号Token"
--> "一、本地有效Token"
if "存在" then
    -->[true] "返回服务号Token" as last
    -left->[Ending process] (*)
else
    -->[false] "二、数据库有效Token" as db
db --> if "存在" then
    -->[true] "保存在本地"
    --> last
else
    -->[falae] "三、请求微信平台接口获取到token、有效期"
    -->"保存在本地、数据库"
    --> last
end if

@enduml