@startmindmap

header 20200515

title 项目整体业务图

* 如祺移动端管理后台

** 设备风险系统
*** 总览
'****_ 应用
'****_ 时间范围
'****_ 上报次数（类别分类统计）
'****_ 首次上报时间（时间范围内）
'****_ 最近上报时间（时间范围内）
'****_ 类别
'*****_ 风险类型
'*****_ APP版本号
'*****_ 设备型号
'*****_ 设备品牌
'*****_ 用户手机号
'*****_ 设备ID
'*****_ 系统版本
*** 记录列表
*** 告警人列表
*** 告警消息列表

** 数据埋点系统
*** 推荐点降级生效记录
*** 算路降级生效记录

@endmindmap