@startuml

skinparam linetype ortho
'left to right direction
'top to bottom direction
'gravity center

header 20200702

title <size:26>**盖亚系统祺点业务架构图**</size>

file "**说明**：如祺出行自建推荐上车点能力。\n通过第三方数据采集、自建算法数据采集、\n定期清洗和整理数据，构建出如祺出行的\n推荐上车点数据库，为推荐上车点场景\n提供数据支撑能力和良好乘客体验。\n\nGeoMesa：时空数据引擎。\nHBAse:分布式的、面向列的开源数据库。" as readme {
}

package "应用" {
   frame 祺点SDK #decb00 {
'    [数据采集服务\n\n1.第三方采集\n2.自建算法采集\n3.离线上报能力] as [数据采集]
    [数据采集服务] as [数据采集]
'    [推荐上车点服务\n\n1.本地DB缓存\n2.个性化推荐（未来计划）] as [推荐上车点]
    [推荐上车点服务] as [推荐上车点]
   }

   frame 埋点SDK {
'       [事件上报\n\n1.祺点兜底成功上报] as [事件上报]
       [事件上报] as [事件上报] #CCCCCC
   }

   埋点SDK .[hidden]right.> 祺点SDK
}
'note left :


readme .[hidden]. 应用

'readme ..应用

package "服务器" {
    frame "祺点系统" #decb00 {
       [数据整理] as [数据整理]
       [数据预处理、保存] as [数据保存]
'       [数据整理\n\n1.定期清洗脏数据\n2.定期算法更新可用数据] as [数据整理]
       [数据查询]
'       [数据中台\n\n1.总数据量\n2.日新增量\n3.日兜底量] as [数据中台]
   }
   frame "埋点系统" {
        [埋点保存] #CCCCCC
   }
   frame "ELK日志监控系统" as [ELK] {
        [接口日志] as [ELK-log] #CCCCCC
'       [map-recommend-point] as [ELK-point]
'       [record-event] as [ELK-event]
      }
}

package "中台系统" {
    frame "数据查看" #CCCCCC
}

'应用 -[hidden]> 服务器

package "数据库" {
    package "GEO数据存储" #decb00 {
        frame Geomesa

    '    frame "GEO数据库-全量数据" as [全量数据] {
    '        database 全量HBase1 as "全量HBase-1
    '            ..
    '            全量HBase-2
    '            ..
    '            .........
    '            ..
    '            全量HBase-N
    '            "
    '    }

        frame "GEO数据库-可用数据" as 可用数据 {
            database 可用HBase1 as "可用HBase-1
            ..
            可用HBase-2
            ..
            .........
            ..
            可用HBase-N
            "
         }

         frame "GEO数据库-全量数据" as 全量数据 {
                 database 全量HBase1 as "全量HBase-1
                     ..
                     全量HBase-2
                     ..
                     .........
    '                 数据来源
                     ..
                     全量HBase-N
                     "
             }

'        Geomesa . 全量数据
'        Geomesa . 可用数据
'        可用数据 . 全量数据
'        Geomesa .[hidden]. 全量数据
'        Geomesa .[hidden]. 可用数据
'        全量数据 .[hidden] 可用数据
    }


'cloud "业务数据存储" {
    frame "业务数据库" {
        database MySQL1  #CCCCCC as "MySQL-1
            ..
            MySQL-2
            ..
            .........
            ..
            MySQL-N
            "
    }
'}
}

'应用 == 服务器
'数据库 -- 服务器
'中台系统 -- 服务器

'[数据采集] ===  [数据保存]
'[推荐上车点] == [数据查询]
'[数据保存] ==== GEO数据存储
'[数据保存] --- Geomesa
'GEO数据存储 -- Geomesa
'Geomesa -- 全量数据

'[数据查询] === GEO数据存储
'[数据查询] ---- Geomesa
'Geomesa ---- 可用数据
'[数据整理] === GEO数据存储
'[数据整理] --- Geomesa
'全量数据 ---- 可用数据

'[数据保存] . [ELK-log]
'[数据查询] . [ELK-log]

'[事件上报] -- [埋点保存]
'[埋点保存] .up. [ELK-log]
'[埋点保存] -- 业务数据库

'GEO数据存储 -[hidden]> 业务数据库
应用 -[hidden]--> 服务器
'服务器 --> 数据库
'应用 -[hidden]> 数据库

祺点系统 -[hidden]> 埋点系统
祺点系统 -[hidden]> ELK
'ELK -[hidden]right-> 埋点系统

[数据保存] -[hidden]> [数据查询]
[数据查询] -[hidden]> [数据整理]
服务器 -[hidden]--> 数据库
'[数据查询] -[hidden]> [数据中台]
'[数据中台] -[hidden]> [数据整理]

中台系统 -[hidden]> 应用

@enduml