@startuml

header 20200630

title 如祺自建推荐上车点时序图

participant 应用层
participant SDK
participant 服务器
participant 数据库

group 数据收集
autonumber
应用层 -> SDK : 调用上报方法
note left : 乘客推荐点、司机滑动到达上车点作为推荐点
activate SDK
SDK -> 服务器 : 上报API接口调用
note left : SDK理论上只提供上报、\n获取两个方法。
activate 服务器
服务器 -> 数据库 : 数据库保存
deactivate 服务器
SDK --> SDK : 实时上报失败走离线上报（第二版实现）
deactivate SDK
end

group 数据清洗
autonumber
activate 服务器
服务器 -> 数据库 : 服务器定时触发数据清晰？
deactivate 服务器
end

group 数据获取
autonumber
应用层 -> SDK : 调用获取方法
activate SDK
SDK -> 服务器 : 获取API接口调用
note left : SDK理论上只提供上报、\n获取两个方法。
activate 服务器
服务器 -> 数据库 : 数据库查询
数据库 -> 服务器 : 返回数据库匹配数据
'服务器 -> 服务器 : 记录
服务器 -> SDK : 返回数据
deactivate 服务器
SDK -> 应用层 : 返回数据用于业务逻辑
note right : 返回数据的再次处理由SDK还是业务做？
deactivate SDK
end

'数据查看
'日新增量（只获取最近5天或10天）
'日兜底量（只获取最近5天或10天）（带订单总量、全部总量）
'1.总数据量（记录数、坐标数）\n2.日新增量（记录数、坐标数）

@enduml